version: '2.4'
services:
 master:
  build:
   context: ${ROOT_DIR}/dockerContexts/spark_Context
   dockerfile: ${ROOT_DIR}/dockerFiles/base-image.Dockerfile
   args:
    -SPARK_WORKER_UI_PORT: "${SPARK_WORKER_UI_PORT}"
    -SPARK_MASTER_UI_PORT: "${SPARK_MASTER_UI_PORT}"
    -SPARK_MASTER_PORT : "${SPARK_MASTER_PORT}"
  image: base-image
  expose:
    - "${SPARK_MASTER_PORT}"
  ports:
    - "${SPARK_MASTER_UI_PORT}:${SPARK_MASTER_UI_PORT}"
  container_name: spark-master
  volumes:
    - ${ROOT_DIR}/dockerContexts/spark_Context/scripts:C:/scripts
  entrypoint: ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass", "C:/scripts/spark-entrypoint.ps1", "Master"]
 
 worker:
  build:
   context: ${ROOT_DIR}/dockerContexts/spark_Context
   dockerfile: ${ROOT_DIR}/dockerFiles/base-image.Dockerfile
   args:
    -SPARK_WORKER_UI_PORT: "${SPARK_WORKER_UI_PORT}"
    -SPARK_MASTER_UI_PORT: "${SPARK_MASTER_UI_PORT}"
    -SPARK_MASTER_PORT : "${SPARK_MASTER_PORT}"
  image: base-image
  ports:
    - "${SPARK_WORKER_UI_PORT}:${SPARK_WORKER_UI_PORT}"
  container_name: spark-worker
  depends_on:
    - master
  volumes:
    - ${ROOT_DIR}/dockerContexts/spark_Context/scripts:C:/scripts
  entrypoint: ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass", "C:/scripts/spark-entrypoint.ps1", "Worker"]

 livy:
  build:
   context: ${ROOT_DIR}/dockerContexts/livy_Context
   dockerfile: ${ROOT_DIR}/dockerFiles/livy-image.Dockerfile
   args:
    -LIVY_SERVER_PORT: "${LIVY_SERVER_PORT}"
  image: livy-image
  ports:
    - "${LIVY_SERVER_PORT}:${LIVY_SERVER_PORT}"
  container_name: spark-livy
  depends_on:
    - master
    - worker
  volumes:
    - ${ROOT_DIR}/dockerContexts/livy_Context/scripts:C:/scripts
  entrypoint: ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass", "C:/scripts/livy-entrypoint.ps1"]

  