version: '2.4'
services:
 master:
  build:
   context: ${ROOT_DIR}/dockerContexts/spark_Context
   dockerfile: ${ROOT_DIR}/dockerFiles/base-image.Dockerfile
  image: davidosullivan/livy-spark-windows-container:base-image
  expose:
    - "${SPARK_MASTER_PORT}"
  ports:
    - "${SPARK_MASTER_UI_PORT}:${SPARK_MASTER_UI_PORT}"
  container_name: spark-master
  environment:
    - SPARK_WORKER_UI_PORT
    - SPARK_MASTER_UI_PORT
    - SPARK_MASTER_PORT
  volumes:
    - ${ROOT_DIR}/dockerContexts/spark_Context/scripts:C:/scripts
  entrypoint: ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass", "C:/scripts/spark-entrypoint.ps1", "Master"]
  networks:
    - spark-livy-network
 
 worker:
  build:
   context: ${ROOT_DIR}/dockerContexts/spark_Context
   dockerfile: ${ROOT_DIR}/dockerFiles/base-image.Dockerfile
  image: davidosullivan/livy-spark-windows-container:base-image
  ports:
    - "${SPARK_WORKER_UI_PORT}:${SPARK_WORKER_UI_PORT}"
  container_name: spark-worker
  depends_on:
    - master
  environment:
    - SPARK_WORKER_UI_PORT
    - SPARK_MASTER_UI_PORT
    - SPARK_MASTER_PORT
  volumes:
    - ${ROOT_DIR}/dockerContexts/spark_Context/scripts:C:/scripts
  entrypoint: ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass", "C:/scripts/spark-entrypoint.ps1", "Worker"]
  networks:
    - spark-livy-network

 livy:
  build:
   context: ${ROOT_DIR}/dockerContexts/livy_Context
   dockerfile: ${ROOT_DIR}/dockerFiles/livy-image.Dockerfile
  image: davidosullivan/livy-spark-windows-container:livy-image
  ports:
    - "${LIVY_SERVER_PORT}:${LIVY_SERVER_PORT}"
  container_name: spark-livy
  environment:
    - LIVY_SERVER_PORT
  depends_on:
    - master
    - worker
  volumes:
    - ${ROOT_DIR}/dockerContexts/livy_Context/scripts:C:/scripts
  entrypoint: ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass", "C:/scripts/livy-entrypoint.ps1"]
  networks:
    - spark-livy-network

networks:
  spark-livy-network:
    name: spark-livy-network

  